### PR TITLE
pass in the job context

### PR DESCRIPTION
**Pull request by xargsgrep**
1. Pass in the JobExecutionContext into doJob so implementing jobs have access to it also.
2. Allow throwing JobExecutionException from doJob so implementing jobs can specify refire upon failures.

### CODE REVIEW

**Comment by MusikPolice** [comment]
This looks like a good idea, but will definitely need to be a new release, as it fundamentally changes the interface for `Job`. I've requested reviews from the other maintainers as well.

**Comment by spinscale** [comment]
looks good, but we should increase the major version here due to the API breakage?

**Comment by grommitz** [comment]
Is there any way the context could be injected instead? That'd be nicer than breaking the api...

**Comment by xargsgrep** [comment]
Another option would be to create an instance variable for the context, then set it before doJob() is called, and create a protected getter method for it so it could be accessed in the child Job class. I don't really like this option but it wouldn't break the API..

Also, the other thing this PR does it allow throwing a JobExecutionException which can be used to control if/how the job gets refired. This will require changing the method signature no matter what.

**Comment by xargsgrep** [comment]
@spinscale Any updates on this?

**Comment by spinscale** [comment]
@MusikPolice feel free to merge this if you want, you got commit superpowers to use them, no need to wait for me or anything like that - I am happy for anyone taking this over, as I dont have too much time to maintain anyway (full time job, few months old new-born, etc :-)

@xargsgrep If you want to help maintain the project, you are more than welcome to. I'm happy to give you commit rights as well.

**Comment by xargsgrep** [comment]
@spinscale Sure, I'd be happy to help maintain if needed.

**Comment by xargsgrep** [comment]
Should I close this PR if breaking the API is not an option? I think it would be very useful to have access to the job context though..

**Comment by spinscale** [comment]
I'm sorry, I forgot you to add the list of committers, did that now... go ahead and do what you think is right, happy for any help. Feel free to break the API, but ensure that you upgrade the major version then.

**Comment by grommitz** [comment]
Yup I'll agree with that - ok to merge subject to updating the major version and documenting the changes in the README

**Comment by xargsgrep** [comment]
@spinscale @grommitz Ok, I've bumped the version to 3.0.0-SNAPSHOT and updated the readme. I can merge it to master but I think @spinscale will have to do the release?

**Pull request merged**
