### PR TITLE
Support for Running in Clustered Environments

### PR DESCRIPTION
**Pull request by MusikPolice**
We use dropwizard-jobs in a clustered environment that typically contains more than one node. This change checks for the existence of a job prior to blindly creating it to avoid firing jobs on every node in the cluster. 

- If there is no existing job with the specified name, it will be created
- If there exists exactly one instance of the job with the specified name, it will be rescheduled, allowing code deployments to update old job schedules
- If there exists more than one instance of the job with the specified name, they will be deleted, and one new instance will be created, enforcing the one-to-one relationship between job name and scheduled job

This change also allows developers to override the default name of jobs annotated with the `@On` and `@Every` annotations by specifying a `jobName` property. 

Finally, the README.md was updated to include a short discussion of using the library in a clustered environment. 

Sorry for the whitespace changes - I tried my best to sync my Eclipse settings with the project defaults, but I inevitably missed a few things that were a pain to track down.

This code has been running on https://live.aeryon.com for approximately 4 months with no issues.

Hope you like it!

### CODE REVIEW

**Comment by MusikPolice** [comment]
@spinscale have you had a chance to review this change yet?

**Comment by MusikPolice** [comment]
@spinscale any input?

**Comment by spinscale** [comment]
@MusikPolice I am not too active anymore on this repo, most of the work is done by @hakandilek with help from @eyalgo and @grommitz 

If you dont mind, I could just give you commit access to the repo, if you are willing to help maintain?

**Comment by MusikPolice** [comment]
@spinscale @hakandilek @eyalgo @grommitz I'd be happy to help maintain going forward. Let me know how we can proceed to get these changes merged, and ideally, push a new version to Maven Central

**Comment by hakandilek** [comment]
@MusikPolice @spinscale it looks good to me.

I've just bumped version up to 1.1.0. I'd be nice if you could resolve conflicts and merge on top of that one. Once done, we can `mvn deploy` to the Maven Central.

PS: Don't forget to add yorself to the contributors list. ;-)

**Comment by spinscale** [comment]
@MusikPolice added you to the list of collaborators

**Comment by MusikPolice** [comment]
@hakandilek @spinscale How do I resolve the conflicts? GitHub tells me I must have write access to the repository to do the merge, and if I do `git merge upstream/master` in my local repository, git tells me that I'm already up to date.

**Comment by MusikPolice** [comment]
@spinscale @hakandilek I can't get Travis to build cleanly. I hate to say this, but the build runs fine on my machine. Here are my details:

```
jfritz@Aine:~/cloud/trunk/dropwizard-jobs$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-100-generic", arch: "amd64", family: "unix"

jfritz@Aine:~/cloud/trunk/dropwizard-jobs$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode
```

I'm not familiar with how Travis works. Based on the error message, it looks like we may be running the tests with a different version of Java than the one that we're using to compile with. That doesn't appear to be the case based on the Travis logs. Any ideas?

**Comment by MusikPolice** [comment]
And done. Thanks for all the help @spinscale @hakandilek

**Pull request merged**
