### PR TITLE
Add Apache License

### LINKED ISSUE #13: License information
Please provide which kind of licence is used in the project.

### PR DESCRIPTION
**Pull request by hakandilek**
This closes #13. 

@spinscale please have a look.

### CODE REVIEW

**Comment by spinscale** [comment]
I think we need to include a header in every source file in order to be sure, according to http://www.apache.org/legal/src-headers.html

**Comment by hakandilek** [comment]
yes you're right. any known tool to do it automatically?

**Comment by eyalgo** [comment]
Perhaps just an element in the pom is enough?
see: http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by spinscale** [comment]
in elasticsearch, we use the maven license plugin, I think we should add that and fail the build if a file is lacking a license. Also it allows you to add the license to all files. See more at the elasticsearch pom file at https://github.com/elasticsearch/elasticsearch/blob/master/pom.xml#L1439-L1475

**Comment by eyalgo** [comment]
That's one way.
But still, looking at Dropwizard's pom, all they did was adding the license element.
https://github.com/dropwizard/dropwizard/blob/master/pom.xml#L152-L158

**Comment by spinscale** [comment]
I am still in favor of doing it the way it is listed on the official page, to be honest.

**Comment by hakandilek** [comment]
This one's been just hanging for a while. Source headers are required only for the projects developed at the ASF by the Apache community. dw-jobs is not an ASF project. A simple licence file is enough to have Apache License.

**Comment by hakandilek** [comment]
I'm just merging this. @spinscale please re-open if you disagree.

**Pull request merged**
