### PR TITLE
@Every jobs configurable via YAML

### PR DESCRIPTION
**Pull request by grommitz**
Hi, I didn't want to rebuild the app every time I wanted to change the interval for my @Every jobs, so I have implemented a way of configuring it in the config file instead. Hopefully the README explains it all. There is a small amount of boilerplate required to make it work, any ideas to reduce it gratefully received. This could easily be extended to @On jobs too if you like it, though that's not implemented yet.

### CODE REVIEW

**Comment by spinscale** [comment]
Sorry for my late reply! November was offline month :-) this looks useful! 

@grommitz I saw you also added another PR. Mind if I just give you commit permissions to the repo? As you can see I clearly dont have enough time for it...

@hakandilek objections?

**Comment by grommitz** [comment]
@spinscale Sure, fine by me

**Comment by hakandilek** [comment]
Yes,  looks fine.

**Comment by spinscale** [comment]
@grommitz all right, added you as a collaborator.. go ahead :-)

**Comment by hakandilek** [comment]
Should we merge this?

**Comment by grommitz** [comment]
Sure, I'll resolve the conflicts first

**Comment by hakandilek** [comment]
Great!

**Comment by grommitz** [comment]
should be ready to merge now...

**Comment by hakandilek** [comment]
Great work. Tests pass, documentation is ok. Thanks @grommitz.

**Pull request merged**
